language: node_js
node_js:
- 10
deploy:
  provider: npm
  email: briandl92391@gmail.com
  api_key:
    secure: cFPvtvzAS3FwKq4vbXkHXOKdLSvPMpYd2WKnsyS01uOla+BGBjr/Hrp3d/QPqyROLjsLeQIFKV/YYK/uty+4n6eknlhPVpfYR/SXu/WKU8iltCkVo8D0Ai2dOMJLpq8o8EYYIFc+L34ZIs9wo/sDTwwQKfRfTyuXQ53z6jlwdxF6IQDrea3SH20ekZookjY7bMi+68xDUvSw28UM6AnDHD/YMAGo+sdSaNxZGw5k4cpY1IrvdIidEiX1oXz8xwEFxrYiASRJnRWPEMaH128XBPcqPlw3X7QCKXVEwHCXdN7pw9nW7ZTYCqdesTNyD0EECVmJNyjscFH6q1gVCp9ZHEZ6dAnVw/DVPyKFIiVLQ1hMaPeUGGVNmTNu0FBBvY087lfhULjyhrxgv2Juvbstg8B03UvSKZYHJ79SHjH+aHOIXLxuQrUvLMjzM8sAbXRpyExYD4lN8txNn0XQSGeVdqWTz1v86Rxm6GKNani0L4+bRvFwow/7wrXs1WLAddNyqLjf4ocPgDG5xlYtaYuRP/+d/TDCSx+cMmqjtJI//3oa/IXUugMmtfN9sjTEXdZNEEH6/+fGgN3twIAJTVwWomBsM6j3QtMCH/PFfq5vFz5pitkY6DVwKOx0Dac2EstIDPbIzgzpoTLP+fzHCa/gcoZnShNsqqSyhCBDyUdqWi4=
  on:
    tags: true
    repo: brian-dlee/tacto
