language: node_js
node_js:
- 10
install:
- npm install -g codecov
- npm install
after_success:
- codecov
deploy:
  provider: releases
  api_key:
    secure: M69D25qaXA8y8N3hwKRDMqc0iCMdS1wvkT2w6+6CAMFsKBNZ3oYCkzCHlWQ3OAZx3MK1U74PMPd35mTgD0zzQ940nNn2c2gxIgRqQcBv4cE55zaPnsdMMymY2mXNB5YKL49H/YHvOVolA8QsHi2Xp/ujTjljrtGcMtMn4LM5hJjyAcViLtS2qNBlKlh7oJ3lOYlPWGgYlvzZx/qYsgYxJKx+kxioAAGjKTYicbxb+UwvGy6HaIQ/xZ6BXYEFY1CMybPRlzENsANUmHmfKhNoyvkujU5Zk34Gj4lgNPrFLv0ljnxeNdd11W7aJu7UdoOtFm6YQMq7BK/EdPVsnXn+ncKZn7PBhkJlr5Zbotrh4M1I2TMizh0V4aORCw9Kem+8qMBa1uvq33WTdy6KMmky5wN1Jg2mlEErWkP789oy1gPEcsv5Ab1sPLv/cRfRR/FraTDVyN/2EVc6qXPCB7Iv3wA9tAalRoYt9v7bWWjk0jRV2319dGcm4c1R5PDZ1dL5H1dhytR3BDZczKjHrtQHqx39XgSRutIbDlSx2IGpqDsLcsVyOQvwHIlUvWosV9yPV2MH/ROfhmk0fNat6bU9bGqAuqd09npPQKmT1fwYmKaqUZnBSpGN1toHLm4gbevHMJXP9giWTiKxk7uxfU6m8ydze3r1bmH4kRE8hPGBzpQ=
  file: ''
  edge: true
  on:
    tags: true
    repo: brian-dlee/tacto
